(define (pascal-triangle i j)
  (cond ((= j 0) 1)
        ((= j i) 1)
        (else (+ (pascal-triangle (- i 1) (- j 1))
                 (pascal-triangle (- i 1) j)))))

; test
(pascal-triangle 0 0)
(pascal-triangle 1 0)
(pascal-triangle 1 1)
(pascal-triangle 2 0)
(pascal-triangle 2 1)
(pascal-triangle 2 2)
(pascal-triangle 4 2)
(pascal-triangle 4 3)
(pascal-triangle 10 0)
(pascal-triangle 10 8)
(pascal-triangle 10 9)
(pascal-triangle 11 9)